name: Auto Update Working Progress

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  USERNAME: ${{ secrets.ACTION_RUNNER_USERNAME }}
  EMAIL: ${{ secrets.ACTION_RUNNER_EMAIL }}

permissions: write-all

jobs:
  check:
    name: Working Progress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - uses: actions/setup-python@main
        with:
          python-version: "3.11"

      - name: Download checkWorkingProgress.py
        run: wget https://github.com/NMLT-NTTMK-K18/Utilities/raw/main/Check%20Working%20Progress/checkWorkingProgress.py -O checkWorkingProgress.py

      - name: Run python script
        run: python checkWorkingProgress.py

      - name: Github commit & push
        continue-on-error: true
        run: |
          rm -rf checkWorkingProgress.py
          wget https://github.com/KevinNitroG/My-Scripts/raw/main/Linux/commitAndPush.sh -O commitAndPush.sh
          ./commitAndPush.sh
